### ISSUE TITLE
¿El plugin está publicado en telegraf?

### ISSUE THREAD

**Issue by dperez-sct** [MrMarble/datadis-telegraf-plugin#2]
Hola, estoy estudiando como usar este plugin en un despliegue sobre kubernetes, no obstante no lo he visto publicado en telegraf, por lo que "creo" que debería crearme una imagen de Docker con el mismo incluido. ¿Es así?

Gracias por el gran trabajo y cuenta con una cerveza de mi parte en cuanto tenga esto funcionando.

**Comment by MrMarble** [comment]
Hola David,
Efectivamente, como indicas, el plug-in no forma parte del directorio de plug-ins de Telegraf, hay que implementarlo manualmente.

Puedes descargarte el binario ya compilado o compilarlo manualmente (fuera o en una de las capas de tu imagen de docker) y posteriormente agregarlo a Telegraf usando esta configuración:

```toml
[[inputs.execd]]
  ## One program to run as daemon.
  ## NOTE: process and each argument should each be their own string
  command = ["/path/to/datadis-telegraf", "--config", "/path/to/plugin.conf"]

  ## Define how the process is signaled on each collection interval.
  ## Valid values are:
  ##   "none"    : Do not signal anything. (Recommended for service inputs)
  ##               The process must output metrics by itself.
  ##   "STDIN"   : Send a newline on STDIN. (Recommended for gather inputs)
  ##   "SIGHUP"  : Send a HUP signal. Not available on Windows. (not recommended)
  ##   "SIGUSR1" : Send a USR1 signal. Not available on Windows.
  ##   "SIGUSR2" : Send a USR2 signal. Not available on Windows.
  signal = "none"

  ## Delay before the process is restarted after an unexpected termination
  restart_delay = "10s"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
  
  # Set interval to 24h
  interval = "24h"
```
